version: "3.8"

services:
  python_app:
    build: ./llm_app
    container_name: python_app
    ports:
      - "5000:5000"

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"

  node_server:
    build: ./node_server
    container_name: node_server
    ports:
      - "3000:3000"
    depends_on:
      - python_app
      - postgres
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/mydb
      DB_HOST: postgres
      DB_PASSWORD: password
      DB_USERNAME: user
      DB_DATABASE: mydb
      DB_PORT: 5432
      LLM_APP_HOST: python_app
      LLM_APP_POST: 5000
